services:
  redis:
    image: redis:7.2-alpine
    command: redis-server --bind 0.0.0.0
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  app:
    image: voice-bot-server:latest
    env_file:
      - .env
    ports:
      - 6000:3000
    depends_on:
      - redis
    environment:
      - REDISHOST=redis
    volumes:
      - ./:/code

  # Observability Stack
  grafana:
    image: grafana/grafana
    ports:
      - "9091:3000"
    volumes:
      - grafana-data:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observe/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  redis_data:
  vb_data:
  grafana-data:  
